## Schedule downtime
#- include: demote.yml
#  tags:
#     - restart
#     - checkmk
#     - stop

# Prepare specific user configuration
- include: sysconf.yml

- include: stop.yml
  tags:
     - restart
     - stop


# Redis and sentinel deploy application and configuration
- include: redis.yml
- include: sentinel.yml

## Redis application restart
- include: start.yml
  tags:
     - restart
     - start

### Remove downtime and put server back on load balancer
##- include: promote.yml
##  tags:
##     - restart
##     - checkmk
##     - start
##
##