---
- name: create sentinel init script
  template:
    src: "redis_sentinel.init.j2"
    dest: /etc/init.d/sentinel
    mode: 0755
  become: true

- name: Deploy Sentinel configuration file
  template:
    src: sentinel.conf.j2
    dest: "{{redis_conf_dir}}/sentinel.conf"
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  become: true

- name: "Enable {{redis_sentinel_service_name}} as a service"
  service:
   name: "{{ redis_sentinel_service_name }}"
   enabled: yes
   state: started
  become: true