---
- name: "Enable redis as a service"
  service:
    name: redis
    state: started
  become: true

- name: "Wait for instances to listen on port redis"
  wait_for:
    state: started
    host: "{{ inventory_hostname }}"
    port: "{{ redis_port }}"
    timeout: "{{ app_timeout }}"
  become: true

- name: "Start sentinel"
  service:
    name: sentinel
    state: started
  become: true

- name: "Wait for instances to listen on port sentinel"
  wait_for:
    state: started
    host: "{{ inventory_hostname }}"
    port: "{{ redis_sentinel_port }}"
    timeout: "{{ app_timeout }}"
  become: true